 SELECT *FROM EMP_1;
 INSERT INTO EMP_1(EMP_NUM, EMP_Lname, EMP_Fname, EMP_INITIAL, EMP_HIREDATE, JOB_CODE)
 VALUES('1', 'Palomo', 'Nemuel Rico', 'O', '2023-03-28', '501');
 INSERT INTO EMP_1(EMP_NUM, EMP_Lname, EMP_Fname, EMP_INITIAL, EMP_HIREDATE, JOB_CODE)
 VALUES('2', 'Orgado', 'Liam', 'O', '2023-03-28', '501');
 
 